### ISSUE TITLE
https://github.com/LonamiWebs/Telethon/issues/4051

### ISSUE THREAD

**Issue by SUBMARlNE** [Bobako/tg_responder#2]
![image](https://github.com/Bobako/tg_responder/assets/84868711/d01b6db7-a537-4216-a7e6-6f2159eebcd1)
Невозможно добавить новые аккаунты, сразу происходит разлогин или бан акков.
Нужно прописать параметры клиента как упоминалось здесь [#4051](https://github.com/LonamiWebs/Telethon/issues/4051)

**Comment by batonseu** [comment]
> Невозможно добавить новые аккаунты в проект, сразу происходит разлогин аккаунтов или их бан. ![image](https://user-images.githubusercontent.com/84868711/244870464-d01b6db7-a537-4216-a7e6-6f2159eebcd1.png)
> 
> Возможно нужно прописать параметры клиента как советуют в этой ветке

**Comment by Asylzatwww** [comment]
did you find out the solution?
